apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- db-configmap.yaml
- db-deployment.yaml
- issuer.yaml
- quiz-secrets.yaml
- sb-server-deployment.yaml
images:
- name: fegrus/quiz-sb-server
  newTag: 0.1.3
